/**
 * Yoyo UI controller.
 *
 * Integration rule:
 * - Keep DOM structure and visual behavior stable.
 * - Replace data access through js/api.js.
 * - Do not place secrets or production URLs in this file.
 */
const { SPECIES, SUGGEST, VETS, answerFor } = window.YoyoAPI.mock;

const $=s=>document.querySelector(s),esc=s=>String(s||"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));

    const state={user:{name:"异宠用户",phone:"18800000000"},pets:[],selected:0,chats:[],active:null,streaming:false,prompted:false,pendingImage:null,petDraftPhoto:null,editingPet:null};let seed=1;const uid=()=>`id${seed++}`;

    const App={
      show(id){document.querySelectorAll(".screen").forEach(x=>x.classList.remove("active"));$(id).classList.add("active")},
      toggleVideo(){const v=$("#heroVideo"),b=$("#videoToggle");if(v.paused){v.play();b.textContent="Ⅱ"}else{v.pause();b.textContent="▶"}},
      openAuth(){$("#modalMount").innerHTML=`<div class="mask" onclick="if(event.target===this)App.closeModal()"><div class="modal"><div class="modal-head"><h2 class="display">登录 Yoyo</h2><button class="close" onclick="App.closeModal()">×</button></div><div class="modal-body"><p class="lead">登录后即可保存宠物档案和历史对话。</p><div class="field"><label>手机号</label><input id="phone" class="input" value="18800000000" maxlength="11" inputmode="numeric"></div><div class="field"><label>验证码</label><div class="row"><input id="codeInput" class="input" placeholder="输入 000000" maxlength="6" inputmode="numeric"><button class="code" onclick="App.sendCode(this)">获取验证码</button></div></div><div class="hint">演示验证码：000000</div><div id="authError" class="error hidden"></div><button class="btn btn-primary submit" onclick="App.login()">进入 Yoyo&nbsp; ↗</button></div></div></div>`;setTimeout(()=>$("#codeInput").focus(),60)},
      sendCode(b){b.textContent="已发送 · 60s";b.disabled=true;this.toast("验证码已发送 · 000000")},
      login(){const p=$("#phone").value.trim(),c=$("#codeInput").value.trim();if(!/^1[3-9]\d{9}$/.test(p)||c!=="000000"){const e=$("#authError");e.classList.remove("hidden");e.textContent="请输入有效手机号和演示验证码 000000";return}state.user.phone=p;this.renderUser();this.closeModal();this.show("#inside");this.renderAll();if(!state.prompted){state.prompted=true;setTimeout(()=>this.openPet(true),220)}},
      renderUser(){const n=state.user.name||"异宠用户",masked=state.user.phone.slice(0,3)+"****"+state.user.phone.slice(7);$("#sideName").textContent=n;$("#sidePhone").textContent=masked;$("#sideAvatar").textContent=n.charAt(0);$("#bigAvatar").textContent=n.charAt(0)},
      goHome(){this.closeSidebar();this.show("#landing")},closeModal(){$("#modalMount").innerHTML=""},
      openPet(first=false,editIndex=null){const editing=editIndex!==null,pet=editing?state.pets[editIndex]:null;if(!editing&&state.pets.length>=5){this.showPetLimit();return}state.editingPet=editing?editIndex:null;state.petDraftPhoto=pet?.photo||null;$("#modalMount").innerHTML=`<div class="mask" onclick="if(event.target===this)App.closeModal()"><div class="modal"><div class="modal-head"><h2 class="display">${editing?"编辑宠物":first?"添加第一只宠物":"添加小伙伴"}</h2><button class="skip" onclick="App.closeModal()">${first&&!editing?"暂不填写":"关闭"}</button></div><div class="modal-body"><p class="lead">${editing?"修改后会同步更新该宠物卡片与后续提问信息。":"最多添加 5 只宠物，每只宠物支持上传 1 张照片作为卡片封面。"}</p><div class="field"><label>宠物照片（仅限一张）</label><div id="petPhotoBox"></div></div><div class="field"><label>昵称</label><input id="petName" class="input" placeholder="比如：十一" value="${esc(pet?.name||"")}"></div><div class="field"><label>品种</label><div class="species-grid" id="species">${SPECIES.map((s,i)=>`<button class="chip ${(pet?pet.species===s:i===0)?"on":""}" data-name="${s}" onclick="App.pickChip(this)">${s}</button>`).join("")}</div></div><div class="field"><label>年龄（可选）</label><input id="petAge" class="input" placeholder="比如：8 个月" value="${esc(pet?.age==="年龄未知"?"":pet?.age||"")}"></div><div class="field"><label>性别</label><div class="sex-grid" id="sex">${["未知","公","母"].map((s,i)=>`<button class="chip ${(pet?pet.sex===s:i===0)?"on":""}" data-value="${s}" onclick="App.pickChip(this)">${s}</button>`).join("")}</div></div><div id="petError" class="error hidden"></div><button class="btn btn-primary submit" onclick="App.savePet()">${editing?"保存修改":"保存宠物档案"}</button></div></div></div>`;this.renderPetPhoto()},
      renderPetPhoto(){const box=$("#petPhotoBox");if(!box)return;box.innerHTML=`<div class="photo-picker">${state.petDraftPhoto?`<img class="photo-preview" src="${state.petDraftPhoto}" alt="宠物照片">`:`<div class="photo-preview" style="display:grid;place-items:center;font-size:26px">＋</div>`}<div class="photo-info"><b>${state.petDraftPhoto?"照片已选择":"上传一张宠物照片"}</b><p>支持 JPG、PNG、WebP，最大 10MB；再次选择会替换当前照片。</p><button class="photo-btn" onclick="App.pickPetPhoto()">${state.petDraftPhoto?"更换照片":"选择照片"}</button></div></div>`},
      pickPetPhoto(){const i=document.createElement("input");i.type="file";i.accept="image/jpeg,image/png,image/webp";i.onchange=()=>{const f=i.files?.[0];if(!f)return;if(f.size>10*1024*1024){this.toast("图片不能超过 10MB");return}state.petDraftPhoto=URL.createObjectURL(f);this.renderPetPhoto()};i.click()},
      pickChip(el){el.parentElement.querySelectorAll(".chip").forEach(x=>x.classList.remove("on"));el.classList.add("on")},
      savePet(){const n=$("#petName").value.trim();if(!n){$("#petError").classList.remove("hidden");$("#petError").textContent="请先填写宠物昵称";return}const pet={name:n,species:$("#species .on").dataset.name,age:$("#petAge").value.trim()||"年龄未知",sex:$("#sex .on").dataset.value,photo:state.petDraftPhoto};if(state.editingPet!==null){state.pets[state.editingPet]=pet;state.selected=state.editingPet}else{state.pets.push(pet);state.selected=state.pets.length-1}const edited=state.editingPet!==null;state.editingPet=null;this.closeModal();this.renderPets();this.toast(edited?`${n} 的档案已更新`:`${n} 的档案保存好了`)},
      showPetLimit(){$("#modalMount").innerHTML=`<div class="mask" onclick="if(event.target===this)App.closeModal()"><div class="modal" style="max-width:390px"><div class="modal-head"><h2 class="display">宠物数量已满</h2><button class="close" onclick="App.closeModal()">×</button></div><div class="modal-body"><p class="lead">目前仅支持上传五个宠物。如需添加新的宠物，请先编辑或移除已有宠物档案。</p><button class="btn btn-primary submit" onclick="App.closeModal()">我知道了</button></div></div></div>`},
      renderAll(){this.renderUser();this.renderPets();this.renderHistory();this.renderSuggestions();this.renderMessages();this.updateView()},
      renderPets(){const colors=["var(--sky)","var(--peach)","var(--butter)","var(--lilac,#ddd2ee)","var(--milk)"];$("#petGrid").innerHTML=state.pets.map((p,i)=>`<div class="pet-card ${p.photo?"has-photo":""} ${i===state.selected?"on":""}" style="${p.photo?`background-image:url('${p.photo}')`:`background:${colors[i%colors.length]}`}" onclick="App.selectPet(${i})">${p.photo?"":`<span class="pet-placeholder">🐾</span>`}<span class="pet-info"><b>${esc(p.name)}</b><small>${esc(p.species)} · ${esc(p.age)}</small></span><span class="pet-actions"><button class="pet-action" onclick="event.stopPropagation();App.editPet(${i})">编辑</button><button class="pet-action ask" onclick="event.stopPropagation();App.askPet(${i})">提问</button></span></div>`).join("");$("#petCount").textContent=`${state.pets.length} / 5`},
      selectPet(i){state.selected=i;this.renderPets();const p=state.pets[i],input=this.current()?.messages.length?$("#chatInput"):$("#heroInput");input.placeholder=`问问关于 ${p.name}（${p.species}）的问题…`;input.focus()},
      editPet(i){this.openPet(false,i)},
      askPet(i){state.selected=i;this.renderPets();const p=state.pets[i],input=this.current()?.messages.length?$("#chatInput"):$("#heroInput");const question=input.value.replace(/^我想咨询「[^」]+」（[^）]*）：\s*/,"");const info=[p.species,p.age,p.sex].filter(Boolean).join("，"),prefix=`我想咨询「${p.name}」（${info}）：`;input.value=prefix+question;input.focus();input.setSelectionRange?.(prefix.length,prefix.length)},
      renderSuggestions(){$("#suggestions").innerHTML=SUGGEST.map(q=>`<button class="suggest" onclick="App.send('hero','${q}')">${q}</button>`).join("")},current(){return state.chats.find(c=>c.id===state.active)},
      newChat(){state.active=null;state.pendingImage=null;this.renderAll();this.renderPreview();this.closeSidebar();$("#heroInput").value=""},openChat(id){state.active=id;this.renderAll();this.closeSidebar()},renderHistory(){$("#history").innerHTML=state.chats.length?state.chats.map(c=>`<div class="history-item ${c.id===state.active?"on":""}" onclick="App.openChat('${c.id}')">${esc(c.title)}</div>`).join(""):`<div class="history-item" style="opacity:.55">还没有对话</div>`},updateView(){const started=this.current()?.messages.length;$("#welcome").classList.toggle("hidden",!!started);$("#chat").classList.toggle("show",!!started)},
      send(where,preset){if(state.streaming)return;const input=where==="hero"?$("#heroInput"):$("#chatInput"),text=String(preset??input.value).trim();if(!text&&!state.pendingImage)return;let c=this.current();if(!c){c={id:uid(),title:text.slice(0,22)||"图片提问",messages:[]};state.chats.unshift(c);state.active=c.id}const p=state.pets[state.selected],context=p?`[${p.name} · ${p.species} · ${p.age} · ${p.sex}] `:"";c.messages.push({role:"user",text:text||"请帮我看看这张图片",context,image:state.pendingImage});input.value="";state.pendingImage=null;this.renderPreview();this.renderHistory();this.updateView();this.renderMessages();const r=answerFor(text||"图片"),m={role:"ai",text:"",high:r.high};c.messages.push(m);state.streaming=true;let i=0;const t=setInterval(()=>{i=Math.min(r.text.length,i+4);m.text=r.text.slice(0,i);this.renderMessages();if(i>=r.text.length){clearInterval(t);state.streaming=false;this.renderMessages();if(r.high)setTimeout(()=>this.openMap("high"),380)}},18)},
      renderMessages(){const c=this.current();if(!c){$("#messagesInner").innerHTML="";return}$("#messagesInner").innerHTML=c.messages.map(m=>{if(m.role==="user")return`<div class="message user"><div class="msg-avatar">我</div><div class="bubble">${m.image?`<img src="${m.image}" alt="用户上传图片">`:""}${m.context?`<span style="display:block;color:#d9f0fa;font-size:8px;margin-bottom:4px">${esc(m.context)}</span>`:""}${esc(m.text)}</div></div>`;const body=m.text.split("\n").map(line=>{const safe=esc(line).replace(/\*\*([^*]+)\*\*/g,"<strong>$1</strong>");return/请立即就医/.test(line)?`<div class="high-risk">${safe}</div>`:`<p>${safe||"&nbsp;"}</p>`}).join("");return`<div class="message ai"><div class="msg-avatar">🐾</div><div class="bubble">${body}${m.high?`<button class="map-entry" onclick="App.openMap('high')">📍 查看附近医院</button>`:""}</div></div>`}).join("");const b=$("#messages");b.scrollTop=b.scrollHeight},
      pickChatImage(){const i=document.createElement("input");i.type="file";i.accept="image/jpeg,image/png,image/webp";i.onchange=()=>{const f=i.files?.[0];if(!f)return;if(f.size>10*1024*1024){this.toast("图片不能超过 10MB");return}state.pendingImage=URL.createObjectURL(f);this.renderPreview();this.toast("图片已添加")};i.click()},renderPreview(){document.querySelectorAll(".preview").forEach(x=>x.remove());if(!state.pendingImage)return;const h=`<div class="preview"><img src="${state.pendingImage}" alt="待发送图片"><span>图片已准备好</span><button onclick="App.clearImage()">移除</button></div>`;$(".ask-foot")?.insertAdjacentHTML("beforebegin",h);$(".composer-inner")?.insertAdjacentHTML("beforebegin",h)},clearImage(){state.pendingImage=null;this.renderPreview()},
      openProfile(){this.closeSidebar();$("#profileName").value=state.user.name;$("#profilePhone").value=state.user.phone;$("#profilePage").classList.remove("hidden")},closeProfile(){$("#profilePage").classList.add("hidden")},saveProfile(){const n=$("#profileName").value.trim(),p=$("#profilePhone").value.trim();if(!n){this.toast("请填写昵称");return}if(!/^1[3-9]\d{9}$/.test(p)){this.toast("请输入有效手机号");return}state.user={name:n,phone:p};this.renderUser();this.toast("个人信息已更新")},logout(){location.reload()},
      openMap(source){$("#modalMount").innerHTML=`<div class="mask" onclick="if(event.target===this)App.closeModal()"><div class="modal"><div class="modal-head"><h2 class="display">附近医院</h2><button class="close" onclick="App.closeModal()">×</button></div><div class="modal-body">${source==="high"?`<div class="risk-note"><b>检测到高危描述</b><br>请优先联系医院并尽快出发。</div>`:""}<p class="lead" style="margin-top:12px">以下为演示数据，出发前请电话确认能否接诊异宠。</p>${VETS.map(v=>`<div class="vet"><div class="vet-name"><span>${v[0]}</span><span>${v[1]}</span></div><p>${v[2]}</p><a href="tel:${v[3]}">致电 ${v[3]} ↗</a></div>`).join("")}</div></div></div>`},
      toggleSidebar(){$("#sidebar").classList.toggle("open")},closeSidebar(){$("#sidebar").classList.remove("open")},toast(t){$("#toastMount").innerHTML=`<div class="toast">${esc(t)}</div>`;clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>$("#toastMount").innerHTML="",2100)}
    };
    document.addEventListener("keydown",e=>{if(e.key==="Escape"){App.closeModal();App.closeProfile()}if(e.key==="Enter"&&!e.shiftKey){if(document.activeElement?.id==="heroInput"){e.preventDefault();App.send("hero")}if(document.activeElement?.id==="chatInput"){e.preventDefault();App.send("chat")}}});window.addEventListener("load",()=>App.renderSuggestions());
